---
- name: Creates back-end directory
  file:
    path: ~/backend
    state: directory

- name: Extract artifact.tar.gz into backend directory
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: Install node packages based on package.json.
  npm:
    path: ~/backend

- name: Starting the app
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start npm -- start